apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: one
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: fleet-local
spec:
  # Everything from this repo will be run in this cluster. You trust me right?
  # repo: "https://github.com/rancher/fleet-examples"
  repo: https://github.com/voje/rancher-fleet
  branch: main
  paths:
  # - sites/one
  # - sites/two
  - sites/three
